CREATE TABLE ORDERED_ITEMS
(
    TRANSACTION_ID      BIGINT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID    VARCHAR(64),
    ORDERED_PRODUCTS     VARCHAR(300),
    CUSTOMER_FIRST_NAME VARCHAR(100),
    CUSTOMER_LAST_NAME      VARCHAR(32),
    CUSTOMER_ADDRESS       VARCHAR(32),
    CUSTOMER_CONTACT       VARCHAR(24),
    CUSTOMER_CITY             VARCHAR(12),
    SHIPPING_ADDRESS  VARCHAR(24),
    CUSTOMER_BILL VARCHAR(24),
    ORDERED_STATUS VARCHAR(24)
);