INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_DESC, QUANTITY, PRODUCT_PRICE, PRODUCT_WEIGHT, PRODUCT_LOCATION)
VALUES ('Rasberry Toothpaste', 'Wellness Care', 'Flavored toothpaste', '20', '2', '1', 'Claire Road');
INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_DESC, QUANTITY, PRODUCT_PRICE, PRODUCT_WEIGHT, PRODUCT_LOCATION)
VALUES ('Orange Toothpaste', 'Wellness Care', 'Flavored toothpaste', '20', '2', '1', 'John Road');
INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_DESC, QUANTITY, PRODUCT_PRICE, PRODUCT_WEIGHT, PRODUCT_LOCATION)
VALUES ('Clear Shampoo', 'Wellness Care', 'Flavored toothpaste', '20', '2', '1', 'Claire Road');
INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_DESC, QUANTITY, PRODUCT_PRICE, PRODUCT_WEIGHT, PRODUCT_LOCATION)
VALUES ('Milo', 'Food', 'Health Drinks', '11', '2', '1', 'John Road');
INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_DESC, QUANTITY, PRODUCT_PRICE, PRODUCT_WEIGHT, PRODUCT_LOCATION)
VALUES ('Dark Coffee', 'Food', 'Dark coffee beans', '16', '2', '1', 'Claire Road');
INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_CATEGORY, PRODUCT_DESC, QUANTITY, PRODUCT_PRICE, PRODUCT_WEIGHT, PRODUCT_LOCATION)
VALUES ('Assam Tea', 'Food', 'Imported assam tea leaves', '7', '2', '1', 'John Road');
