CREATE TABLE PRODUCTS
(
    PRODUCT_ID      BIGINT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_NAME    VARCHAR(64),
    PRODUCT_CATEGORY     VARCHAR(64),
    PRODUCT_DESC VARCHAR(64),
    QUANTITY       NUMBER(64),
    PRODUCT_PRICE       VARCHAR(32),
    PRODUCT_WEIGHT         VARCHAR(12),
    PRODUCT_LOCATION  VARCHAR(24)
);